---
name: 🐛 버그 리포트
about: 버그를 발견했을 때 사용하는 템플릿
title: '[BUG] '
labels: ['bug', 'triage']
assignees: ''
---

## 🐛 버그 설명
버그에 대한 명확하고 간결한 설명을 작성해주세요.

## 🔄 재현 단계
버그를 재현하기 위한 단계:
1. '...' 페이지로 이동
2. '...' 버튼 클릭
3. '...' 입력
4. 오류 발생 확인

## 🎯 예상 동작
정상적으로 작동했을 때 예상되는 동작을 설명해주세요.

## 📷 스크린샷
가능하다면 스크린샷을 첨부해주세요.

## 🖥️ 환경 정보
- OS: [예: Windows 11]
- 브라우저: [예: Chrome 120]
- 버전: [예: v1.2.3]

## 📝 추가 정보
버그와 관련된 추가 정보가 있다면 작성해주세요.