---
name: ✨ 기능 요청
about: 새로운 기능을 제안할 때 사용하는 템플릿
title: '[FEATURE] '
labels: ['enhancement', 'feature']
assignees: ''
---

## 🎯 기능 설명
어떤 기능을 원하는지 명확하게 설명해주세요.

## 💡 동기
이 기능이 왜 필요한지, 어떤 문제를 해결하는지 설명해주세요.

## 📋 상세 요구사항
- [ ] 요구사항 1
- [ ] 요구사항 2
- [ ] 요구사항 3

## 🎨 UI/UX 제안
가능하다면 UI/UX에 대한 아이디어나 스케치를 공유해주세요.

## 🔗 참고 자료
관련된 링크나 참고 자료가 있다면 공유해주세요.

## 📊 우선순위
- [ ] 높음 (즉시 필요)
- [ ] 보통 (다음 스프린트)
- [ ] 낮음 (나중에 고려)