name: 📖 사용자 스토리
description: 사용자 스토리 작성 시 사용하는 템플릿
title: "[USER STORY] "
labels: ["user-story"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        사용자 관점에서 필요한 기능을 구체적으로 작성해주세요.

  - type: dropdown
    id: user-type
    attributes:
      label: 👤 사용자 유형
      description: 어떤 사용자를 위한 스토리인가요?
      options:
        - 새로운 사용자
        - 기존 사용자
        - 관리자
        - 게스트 사용자
        - 프리미엄 사용자
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: 📝 사용자 스토리
      description: '"As a [사용자], I want [기능], So that [목적]"식으로 작성해주세요.'
      placeholder: |
        As a 새로운 사용자
        I want 이메일과 비밀번호로 회원가입하고 싶어요
        So that 나만의 할 일 목록을 만들고 관리할 수 있어요
    validations:
      required: true

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: ✅ 인수 조건 (Acceptance Criteria)
      description: 이 스토리가 완료되었다고 판단할 수 있는 구체적인 조건들
      options:
        - label: 조건 1을 여기에 작성해주세요
        - label: 조건 2를 여기에 작성해주세요
        - label: 조건 3을 여기에 작성해주세요

  - type: textarea
    id: additional-criteria
    attributes:
      label: 📋 추가 인수 조건
      description: 위의 체크박스로 표현하기 어려운 조건들을 자유롭게 작성해주세요.
      placeholder: |
        - 이메일 형식 유효성 검사 필수
        - 비밀번호는 8자 이상 영문+숫자 조합
        - 회원가입 성공 시 환영 메시지 표시

  - type: checkboxes
    id: tasks
    attributes:
      label: 🔧 작업 목록 (Tasks)
      description: 이 스토리를 완성하기 위해 필요한 개발 작업들
      options:
        - label: UI 컴포넌트 설계 및 구현
        - label: API 엔드포인트 개발
        - label: 데이터베이스 스키마 설계
        - label: 유효성 검사 로직 구현
        - label: 단위 테스트 작성
        - label: 통합 테스트 작성
        - label: 문서 업데이트

  - type: checkboxes
    id: definition-of-done
    attributes:
      label: 🎯 완료 정의 (Definition of Done)
      description: 이 스토리가 "완료"되었다고 할 수 있는 기준
      options:
        - label: 코드 작성 완료
        - label: 단위 테스트 작성 및 통과
        - label: 코드 리뷰 완료
        - label: 통합 테스트 통과
        - label: 문서 업데이트 완료
        - label: QA 테스트 통과
        - label: 스테이징 환경 배포 완료

  - type: dropdown
    id: story-points
    attributes:
      label: 📊 예상 스토리 포인트
      description: 이 스토리의 복잡도와 작업량을 추정해주세요.
      options:
        - 1 (매우 작음 - 1일 이내)
        - 2 (작음 - 1-2일)
        - 3 (보통 - 2-3일)
        - 5 (큼 - 3-5일)
        - 8 (매우 큼 - 1주일 이상)
        - 13 (거대함 - 더 작게 나눠야 함)
      default: 2

  - type: input
    id: related-epic
    attributes:
      label: 🔗 관련 Epic
      description: 이 스토리가 속한 Epic의 이슈 번호를 입력해주세요.
      placeholder: "#1"

  - type: textarea
    id: dependencies
    attributes:
      label: 🔄 의존성
      description: 이 스토리 완료를 위해 먼저 완료되어야 하는 다른 이슈들
      placeholder: |
        - #5 사용자 인증 API 구현
        - #7 데이터베이스 스키마 설계

  - type: textarea
    id: notes
    attributes:
      label: 📝 추가 메모
      description: 개발 시 참고할 추가 정보나 제약사항
      placeholder: |
        - 반응형 디자인 필수
        - 접근성 가이드라인 준수
        - 기존 디자인 시스템 활용