---
name: 📖 사용자 스토리
about: 사용자 스토리 작성 시 사용하는 템플릿
title: '[USER STORY] '
labels: ['user-story']
assignees: ''
---

## 👤 사용자 스토리
**As a** [사용자 유형]  
**I want** [원하는 기능]  
**So that** [목적/이유]

## ✅ 인수 조건 (Acceptance Criteria)
- [ ] 조건 1: 구체적이고 측정 가능한 조건
- [ ] 조건 2: 구체적이고 측정 가능한 조건
- [ ] 조건 3: 구체적이고 측정 가능한 조건

## 📋 작업 목록 (Tasks)
- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

## 🎯 완료 정의 (Definition of Done)
- [ ] 코드 작성 완료
- [ ] 단위 테스트 작성
- [ ] 코드 리뷰 완료
- [ ] 통합 테스트 통과
- [ ] 문서 업데이트

## 📊 예상 스토리 포인트
[ ] 1 (매우 작음) [ ] 2 (작음) [ ] 3 (보통) [ ] 5 (큼) [ ] 8 (매우 큼)

## 🔗 관련 이슈
- Epic: #
- 의존성: #